name: seapedia
services:
  - name: seapedia-server
    environment_slug: python
    dockerfile_path: server/Dockerfile
    source_dir: server
    envs:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: CLOUDINARY_CLOUD_NAME
        scope: RUN_TIME
        type: SECRET
      - key: CLOUDINARY_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: CLOUDINARY_API_SECRET
        scope: RUN_TIME
        type: SECRET
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    run_command: python manage.py collectstatic --noinput && python manage.py migrate --noinput && gunicorn --bind 0.0.0.0:$PORT server.wsgi:application
